services:
  api:
    build: .
    ports:
      - "8001:8001"
    env_file: .env
    depends_on:
      - redis
    volumes:
      - .:/app

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
